import CACHE_FIRST from './CACHE_FIRST';
import CACHE_ONLY from './CACHE_ONLY';
import FETCHER_FIRST from './FETCHER_FIRST';
import FETCHER_ONLY from './FETCHER_ONLY';
import LAZY_LOAD from './LAZY_LOAD';
import STALE_WHILE_REVALIDATE from './STALE_WHILE_REVALIDATE';

export default {
  CACHE_FIRST,
  CACHE_ONLY,
  FETCHER_FIRST,
  FETCHER_ONLY,
  LAZY_LOAD,
  STALE_WHILE_REVALIDATE,
};
